In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df_app=pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\banks\application_data.csv")
df_app

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# dataframe.head([5])
df_app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df_app.tail()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_app.index

RangeIndex(start=0, stop=49999, step=1)

In [9]:
df_app.shape

(49999, 122)

In [10]:
df_app.size

6099878

In [11]:
df_app.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [12]:
df_app.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [13]:
df_app.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 122 columns):
 #    Column                        Non-Null Count  Dtype
---   ------                        --------------  -----
 0    SK_ID_CURR                    49999 non-null  int64
 1    TARGET                        49999 non-null  int64
 2    NAME_CONTRACT_TYPE            49999 non-null  object
 3    CODE_GENDER                   49999 non-null  object
 4    FLAG_OWN_CAR                  49999 non-null  object
 5    FLAG_OWN_REALTY               49999 non-null  object
 6    CNT_CHILDREN                  49999 non-null  int64
 7    AMT_INCOME_TOTAL              49999 non-null  float64
 8    AMT_CREDIT                    49999 non-null  float64
 9    AMT_ANNUITY                   49998 non-null  float64
 10   AMT_GOODS_PRICE               49961 non-null  float64
 11   NAME_TYPE_SUITE               49807 non-null  object
 12   NAME_INCOME_TYPE              49999 non-null  object
 13   NAME_EDUCATION_TYPE           49999 non-null  object
 14   NAME_FAMILY_STATUS            49999 non-null  object
 15   NAME_HOUSING_TYPE             49999 non-null  object
 16   REGION_POPULATION_RELATIVE    49999 non-null  float64
 17   DAYS_BIRTH                    49999 non-null  int64
 18   DAYS_EMPLOYED                 49999 non-null  int64
 19   DAYS_REGISTRATION             49999 non-null  int64
 20   DAYS_ID_PUBLISH               49999 non-null  int64
 21   OWN_CAR_AGE                   17049 non-null  float64
 22   FLAG_MOBIL                    49999 non-null  int64
 23   FLAG_EMP_PHONE                49999 non-null  int64
 24   FLAG_WORK_PHONE               49999 non-null  int64
 25   FLAG_CONT_MOBILE              49999 non-null  int64
 26   FLAG_PHONE                    49999 non-null  int64
 27   FLAG_EMAIL                    49999 non-null  int64
 28   OCCUPATION_TYPE               34345 non-null  object
 29   CNT_FAM_MEMBERS               49998 non-null  float64
 30   REGION_RATING_CLIENT          49999 non-null  int64
 31   REGION_RATING_CLIENT_W_CITY   49999 non-null  int64
 32   WEEKDAY_APPR_PROCESS_START    49999 non-null  object
 33   HOUR_APPR_PROCESS_START       49999 non-null  int64
 34   REG_REGION_NOT_LIVE_REGION    49999 non-null  int64
 35   REG_REGION_NOT_WORK_REGION    49999 non-null  int64
 36   LIVE_REGION_NOT_WORK_REGION   49999 non-null  int64
 37   REG_CITY_NOT_LIVE_CITY        49999 non-null  int64
 38   REG_CITY_NOT_WORK_CITY        49999 non-null  int64
 39   LIVE_CITY_NOT_WORK_CITY       49999 non-null  int64
 40   ORGANIZATION_TYPE             49999 non-null  object
 41   EXT_SOURCE_1                  21827 non-null  float64
 42   EXT_SOURCE_2                  49873 non-null  float64
 43   EXT_SOURCE_3                  40055 non-null  float64
 44   APARTMENTS_AVG                24614 non-null  float64
 45   BASEMENTAREA_AVG              20800 non-null  float64
 46   YEARS_BEGINEXPLUATATION_AVG   25605 non-null  float64
 47   YEARS_BUILD_AVG               16760 non-null  float64
 48   COMMONAREA_AVG                15039 non-null  float64
 49   ELEVATORS_AVG                 23348 non-null  float64
 50   ENTRANCES_AVG                 24804 non-null  float64
 51   FLOORSMAX_AVG                 25124 non-null  float64
 52   FLOORSMIN_AVG                 16105 non-null  float64
 53   LANDAREA_AVG                  20278 non-null  float64
 54   LIVINGAPARTMENTS_AVG          15773 non-null  float64
 55   LIVINGAREA_AVG                24862 non-null  float64
 56   NONLIVINGAPARTMENTS_AVG       15285 non-null  float64
 57   NONLIVINGAREA_AVG             22427 non-null  float64
 58   APARTMENTS_MODE               24614 non-null  float64
 59   BASEMENTAREA_MODE             20800 non-null  float64
 60   YEARS_BEGINEXPLUATATION_MODE  25605 non-null  float64
 61   YEARS_BUILD_MODE              16760 non-null  float64
 62   COMMONAREA_MODE               15039 non-null  float64
 63   ELEVATORS_MODE                23348 non-null  float64
 64   ENTRANCES_MODE                24804 non-null  float64
 65   FLOORSMAX_MODE                25124 non-null  float64
 66   FLOORSMIN_MODE                16105 non-null  float64
 67   LANDAREA_MODE                 20278 non-null  float64
 68   LIVINGAPARTMENTS_MODE         15773 non-null  float64
 69   LIVINGAREA_MODE               24862 non-null  float64
 70   NONLIVINGAPARTMENTS_MODE      15285 non-null  float64
 71   NONLIVINGAREA_MODE            22427 non-null  float64
 72   APARTMENTS_MEDI               24614 non-null  float64
 73   BASEMENTAREA_MEDI             20800 non-null  float64
 74   YEARS_BEGINEXPLUATATION_MEDI  25605 non-null  float64
 75   YEARS_BUILD_MEDI              16760 non-null  float64
 76   COMMONAREA_MEDI               15039 non-null  float64
 77   ELEVATORS_MEDI                23348 non-null  float64
 78   ENTRANCES_MEDI                24804 non-null  float64
 79   FLOORSMAX_MEDI                25124 non-null  float64
 80   FLOORSMIN_MEDI                16105 non-null  float64
 81   LANDAREA_MEDI                 20278 non-null  float64
 82   LIVINGAPARTMENTS_MEDI         15773 non-null  float64
 83   LIVINGAREA_MEDI               24862 non-null  float64
 84   NONLIVINGAPARTMENTS_MEDI      15285 non-null  float64
 85   NONLIVINGAREA_MEDI            22427 non-null  float64
 86   FONDKAPREMONT_MODE            15808 non-null  object
 87   HOUSETYPE_MODE                24924 non-null  object
 88   TOTALAREA_MODE                25851 non-null  float64
 89   WALLSMATERIAL_MODE            24540 non-null  object
 90   EMERGENCYSTATE_MODE           26301 non-null  object
 91   OBS_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 92   DEF_30_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 93   OBS_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 94   DEF_60_CNT_SOCIAL_CIRCLE      49831 non-null  float64
 95   DAYS_LAST_PHONE_CHANGE        49998 non-null  float64
 96   FLAG_DOCUMENT_2               49999 non-null  int64
 97   FLAG_DOCUMENT_3               49999 non-null  int64
 98   FLAG_DOCUMENT_4               49999 non-null  int64
 99   FLAG_DOCUMENT_5               49999 non-null  int64
 100  FLAG_DOCUMENT_6               49999 non-null  int64
 101  FLAG_DOCUMENT_7               49999 non-null  int64
 102  FLAG_DOCUMENT_8               49999 non-null  int64
 103  FLAG_DOCUMENT_9               49999 non-null  int64
 104  FLAG_DOCUMENT_10              49999 non-null  int64
 105  FLAG_DOCUMENT_11              49999 non-null  int64
 106  FLAG_DOCUMENT_12              49999 non-null  int64
 107  FLAG_DOCUMENT_13              49999 non-null  int64
 108  FLAG_DOCUMENT_14              49999 non-null  int64
 109  FLAG_DOCUMENT_15              49999 non-null  int64
 110  FLAG_DOCUMENT_16              49999 non-null  int64
 111  FLAG_DOCUMENT_17              49999 non-null  int64
 112  FLAG_DOCUMENT_18              49999 non-null  int64
 113  FLAG_DOCUMENT_19              49999 non-null  int64
 114  FLAG_DOCUMENT_20              49999 non-null  int64
 115  FLAG_DOCUMENT_21              49999 non-null  int64
 116  AMT_REQ_CREDIT_BUREAU_HOUR    43265 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_DAY     43265 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_WEEK    43265 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_MON     43265 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_QRT     43265 non-null  float64
 121  AMT_REQ_CREDIT_BUREAU_YEAR    43265 non-null  float64
dtypes: float64(64), int64(42), object(16)
memory usage: 46.5+ MB

In [14]:
df_app.sample(n=30)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
38732,144862,0,Cash loans,F,N,Y,0,189000.0,450000.0,21888.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
38128,144148,0,Cash loans,F,N,Y,2,202500.0,450000.0,32877.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
48183,155801,0,Cash loans,F,N,Y,0,176400.0,770328.0,25587.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
20904,124358,0,Cash loans,F,N,Y,0,117000.0,536917.5,17874.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
12117,114132,0,Revolving loans,F,N,Y,1,67500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
1583,101854,0,Cash loans,F,N,Y,1,202500.0,599116.5,25515.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
27224,131638,0,Cash loans,M,Y,Y,0,270000.0,1080000.0,57672.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
25312,129440,0,Cash loans,F,N,N,0,52650.0,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
13264,115467,0,Revolving loans,F,N,Y,0,112500.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
14755,117222,0,Cash loans,F,Y,Y,0,57150.0,76410.0,7686.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
34632,140133,0,Cash loans,M,Y,Y,2,225000.0,552555.0,33934.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
35522,141143,0,Cash loans,M,Y,Y,1,270000.0,640080.0,31131.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
23205,127002,0,Cash loans,F,Y,N,2,157500.0,758214.0,32256.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
33279,138555,0,Cash loans,M,N,Y,0,76500.0,302206.5,18391.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
44164,151161,0,Cash loans,F,N,Y,0,382500.0,765000.0,39739.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
18747,121861,0,Cash loans,M,N,Y,0,81000.0,108801.0,8851.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
7116,108284,0,Cash loans,M,N,Y,1,270000.0,1008117.0,32652.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
41037,147524,1,Cash loans,F,N,N,1,270000.0,675000.0,21906.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
16892,119699,0,Cash loans,F,N,Y,0,94500.0,180000.0,17397.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,4.0
38248,144291,0,Cash loans,F,N,N,0,202500.0,1535553.0,44136.0,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,0.0
25856,130060,0,Cash loans,F,N,Y,0,126000.0,450000.0,24543.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16295,119004,0,Revolving loans,F,Y,Y,0,135000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
28735,133390,0,Cash loans,F,N,Y,0,45000.0,225000.0,9909.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5792,106772,0,Cash loans,F,Y,Y,0,270000.0,450000.0,30204.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
24187,128128,0,Cash loans,F,N,Y,1,202500.0,229500.0,13302.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
7031,108189,0,Cash loans,F,Y,Y,0,99000.0,900000.0,26446.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
31590,136641,0,Revolving loans,F,N,Y,0,135000.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
2296,102687,0,Cash loans,F,N,N,0,81000.0,466416.0,12955.5,...,1,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
39418,145647,0,Cash loans,F,N,N,0,67500.0,1078200.0,31653.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
29456,134201,0,Cash loans,F,N,N,0,112500.0,382500.0,30217.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
df_app.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='object', length=122)

In [18]:
df_app.columns.to_list()

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [20]:
# it return data frame 
df_app.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,49999.000000,49999.000000,49999.000000,4.999900e+04,4.999900e+04,49998.000000,4.996100e+04,49999.000000,49999.000000,49999.000000,...,49999.000000,49999.000000,49999.000000,49999.00000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000
mean,129013.210584,0.080522,0.419848,1.707676e+05,5.997006e+05,27107.377355,5.390600e+05,0.020798,-16022.042081,63219.424488,...,0.008500,0.000700,0.000520,0.00038,0.007096,0.007512,0.032382,0.270288,0.260973,1.881035
std,16690.512048,0.272102,0.724039,5.318191e+05,4.024154e+05,14562.944435,3.698533e+05,0.013761,4361.400270,140794.605668,...,0.091805,0.026449,0.022798,0.01949,0.087709,0.107992,0.194080,0.928560,0.606996,1.865054
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,2052.000000,4.500000e+04,0.000533,-25184.000000,-17531.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,114570.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16456.500000,2.385000e+05,0.010006,-19644.000000,-2786.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,129076.000000,0.000000,0.000000,1.458000e+05,5.147775e+05,24939.000000,4.500000e+05,0.018850,-15731.000000,-1221.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,143438.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12378.500000,-292.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,157875.000000,1.000000,11.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7680.000000,365243.000000,...,1.000000,1.000000,1.000000,1.00000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [21]:
df_app.describe(include="all")

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,49999.000000,49999.000000,49999,49999,49999,49999,49999.000000,4.999900e+04,4.999900e+04,49998.000000,...,49999.000000,49999.000000,49999.000000,49999.00000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000,43265.000000
unique,NaN,NaN,2,3,2,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Cash loans,F,N,Y,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,45276,32823,32949,34691,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,129013.210584,0.080522,NaN,NaN,NaN,NaN,0.419848,1.707676e+05,5.997006e+05,27107.377355,...,0.008500,0.000700,0.000520,0.00038,0.007096,0.007512,0.032382,0.270288,0.260973,1.881035
std,16690.512048,0.272102,NaN,NaN,NaN,NaN,0.724039,5.318191e+05,4.024154e+05,14562.944435,...,0.091805,0.026449,0.022798,0.01949,0.087709,0.107992,0.194080,0.928560,0.606996,1.865054
min,100002.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,2.565000e+04,4.500000e+04,2052.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,114570.500000,0.000000,NaN,NaN,NaN,NaN,0.000000,1.125000e+05,2.700000e+05,16456.500000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,129076.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,1.458000e+05,5.147775e+05,24939.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,143438.500000,0.000000,NaN,NaN,NaN,NaN,1.000000,2.025000e+05,8.086500e+05,34596.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,157875.000000,1.000000,NaN,NaN,NaN,NaN,11.000000,1.170000e+08,4.050000e+06,258025.500000,...,1.000000,1.000000,1.000000,1.00000,3.000000,6.000000,6.000000,24.000000,8.000000,25.000000

In [24]:
list(set(df_app.columns)-set(df_app.describe().columns))

['FLAG_OWN_REALTY',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'NAME_EDUCATION_TYPE',
 'ORGANIZATION_TYPE',
 'CODE_GENDER',
 'NAME_TYPE_SUITE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'WEEKDAY_APPR_PROCESS_START',
 'EMERGENCYSTATE_MODE',
 'WALLSMATERIAL_MODE',
 'NAME_INCOME_TYPE',
 'NAME_CONTRACT_TYPE',
 'FLAG_OWN_CAR',
 'OCCUPATION_TYPE']

In [26]:
df_app.nunique()

SK_ID_CURR                    49999
TARGET                            2
NAME_CONTRACT_TYPE                2
CODE_GENDER                       3
FLAG_OWN_CAR                      2
                              ...
AMT_REQ_CREDIT_BUREAU_DAY         7
AMT_REQ_CREDIT_BUREAU_WEEK        7
AMT_REQ_CREDIT_BUREAU_MON        20
AMT_REQ_CREDIT_BUREAU_QRT         9
AMT_REQ_CREDIT_BUREAU_YEAR       19
Length: 122, dtype: int64

In [30]:
df_app["CODE_GENDER"].nunique()

3

In [31]:
df_app["CODE_GENDER"].unique()

array(['M', 'F', 'XNA'], dtype=object)